services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:latest@sha256:d98223eb82661a9f6624a813ed7fc44ad4f80e761e24116a721e1cd891ac8c3f
    container_name: BentoPDF
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 3183:8080
    restart: on-failure:5