services:
  homeassistant:
    image: homeassistant/home-assistant:2026.1.3@sha256:c36741490472518338323db8ee67775d7df70d2fa1f68eff9b9e63679fe64a18
    env_file:
      - /volume2/FastSSD/docker/homeassistant/.env
    container_name: Home-Assistant
    mem_limit: 8g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
     test: curl -f http://localhost:8123/ || exit 1
    network_mode: host
    volumes:
      - /volume2/FastSSD/docker/homeassistant:/config:rw
    environment:
      TZ: Europe/Dublin
    restart: on-failure:5
