services:
  homeassistant:
    image: homeassistant/home-assistant:2026.2.2@sha256:3e2dff545c46e91f4ab2b21597016011d76d0de58bc8eaf51d75e841f337bf88
    env_file:
      - /volume2/FastSSD/docker/homeassistant/.env
    container_name: Home-Assistant
    mem_limit: 8g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
     test: curl -f http://localhost:8123/ || exit 1
    network_mode: host
    volumes:
      - /volume2/FastSSD/docker/homeassistant:/config:rw
    environment:
      TZ: Europe/Dublin
    restart: on-failure:5
