services:
  homeassistant:
    image: homeassistant/home-assistant:2026.2.1@sha256:17441c45ba14560b4ef727ee06aac4d605cf0dc0625fc4f2e043cb2551d72749
    env_file:
      - /volume2/FastSSD/docker/homeassistant/.env
    container_name: Home-Assistant
    mem_limit: 8g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
     test: curl -f http://localhost:8123/ || exit 1
    network_mode: host
    volumes:
      - /volume2/FastSSD/docker/homeassistant:/config:rw
    environment:
      TZ: Europe/Dublin
    restart: on-failure:5
