services:
  portainer:
    image: portainer/portainer-ce@sha256:9012a4256c4632f2c6162da361a4d4db9d6d04800e0db0137de96e31656ab876
    env_file:
      - /volume2/FastSSD/docker/portainer/.env
    container_name: Portainer2
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /volume2/FastSSD/docker/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
