services:
 sonarr:
    image: ghcr.io/linuxserver/sonarr:latest@sha256:8b9f2138ec50fc9e521960868f79d2ad0d529bc610aef19031ea8ff80b54c5e0
    env_file:
      - .env
    container_name: Sonarr
    network_mode: host
    healthcheck:
     test: curl -f http://localhost:8989/ || exit 1
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config/sonarr:/config
      - /volume1/SlowHDD/tvseries:/tv:rw #If you want, you can change the following line /volume1/docker/sonarr/tv with the path Location of your own Movie library.
      - /volume2/FastSSD/docker/sonarr/downloads:/downloads:rw #If you want, you can change the following line /volume1/docker/sonarr/downloads with the path Location of your Download folder.
      - /volume2/FastSSD/docker/sonarr/config:/config:rw 
    environment:
      - PUID=1000
      - PGID=10
      - TZ=Europe/Dublin
    ports:
      - 8989:8989
