services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:2.59.02@sha256:42553e381f00704a9686c4c220e4063cb77ba4e3d1819455263ec23a66a58755
    
    # 1. Loads all config (IPs, Ports, Drivers, PUID) from the file
    env_file:
      - /volume2/FastSSD/docker/tdarr/.env
      
    container_name: Tdarr
    hostname: tdarr
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8265/ || exit 1
    ports:
      - 8265:8265
      - 8266:8266
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "105"
    environment:
      - PUID=1000
      - PGID=10
      - UMASK_SET=002
      - TZ=Europe/Dublin      
    volumes:
      - /volume2/FastSSD/docker/tdarr/server:/app/server
      - /volume2/FastSSD/docker/tdarr/configs:/app/configs
      - /volume2/FastSSD/docker/tdarr/logs:/app/logs
      - /volume1/SlowHDD:/media
      - /volume2/FastSSD/docker/tdarr/temp:/temp
    restart: always
