services:
  dozzle:
    image: amir20/dozzle:v10.0.4@sha256:626e30d0df54ea1a5d1ecfbe01337d93813af2789e823c17a69afcd7fcce0c3a
    env_file:
      - /volume2/FastSSD/docker/dozzle/.env
    container_name: Dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9989:8080  # Access it at http://<nas-ip>:9989
    restart: unless-stopped
