services:
  dozzle:
    image: amir20/dozzle:v10.0.6@sha256:4815df572d135ce24c14ec3c150e482c98693bc5cc20291693b582baab8eb0bf
    env_file:
      - /volume2/FastSSD/docker/dozzle/.env
    container_name: Dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9989:8080  # Access it at http://<nas-ip>:9989
    restart: unless-stopped
