services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.4@sha256:1f8dbaaa4c7c2855c2aef711842d13b0c20bfdc3f28ad88faf66aa1bc219b108
    
    # 1. Loads FRIGATE_RTSP_PASSWORD directly into the container
    env_file:
      - /volume2/FastSSD/docker/frigate/.env
      
    container_name: Frigate
    hostname: frigate
    restart: on-failure:5
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    shm_size: 512mb
    
    environment:
      - TZ=Europe/Dublin
      # DELETED: FRIGATE_RTSP_PASSWORD=${RTSP_PASS}
      # (The container now has FRIGATE_RTSP_PASSWORD set automatically)
      
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/FastSSD/docker/frigate/config:/config:rw
      - /volume1/SlowHDD/photos/Frigate_Cameras:/media/frigate:rw
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5563:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
