# config.yml
libraries:
  Movies:
    collection_files:
    - file: movies.yml
    # Tells Kometa to apply these rules to BOTH Plex and Jellyfin
    plex:
      url: http://192.168.1.X:32400
      token: gfrPPXG4TgX-1gitUxHc
      library_name: Movies
    jellyfin:
      url: http://192.168.1.X:8096
      token: b109cd9b54814f338e973b9f53d18e7a
      library_name: Movies

  TV Shows:
    collection_files:
    - file: tvshows.yml
    plex:
      url: http://192.168.1.X:32400
      token: gfrPPXG4TgX-1gitUxHc
      library_name: TV Shows
    jellyfin:
      url: http://192.168.1.X:8096
      token: b109cd9b54814f338e973b9f53d18e7a
      library_name: Shows

settings:
  cache_expiration: 60
  asset_directory: config/assets
  asset_depth: 0
  create_asset_folders: false
  tmdb:
    apikey: ${KOMETA_TMDB_API_KEY}

# Trakt Authentication (Free Account)
# You will need to run the container once interactively to generate these,
# or follow the Kometa wiki to authorize via browser.
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  default_collection_order:
  minimum_items: 1
  item_refresh_delay: 0
  delete_below_minimum: false
  delete_not_scheduled: false
  run_again_delay: 0
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_unfiltered: false
  show_options: false
  show_missing: true
  save_report: false
  tvdb_language: default
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_users:
  playlist_exclude_users:
  playlist_report: true
  custom_repo:
  overlay_artwork_filetype: webp_lossy
  overlay_artwork_quality: 90
trakt:
  client_id: 801e0e82452c6111a714de35f3a24646c94daa5461cfce41edb5d9d175be9cbb
  client_secret: 5452d5057dffecacf9ffe18c4f21d4ab60c0f6f9e1723f7069998232d42fcd22
  pin: # 9394
