services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:latest@sha256:e69e01a503d3b74504295ecc390752235029455a287ebf97402a9ac68760dc72
    container_name: music-assistant-server
    networks:
      - web_proxy
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    # network_mode: host
    volumes:
      - /volume2/FastSSD/docker/music-assistant-server/data:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info
networks:
  web_proxy:
    external: true
