version: '3.8'
services:
  retroassembly:
    image: arianrhodsandlot/retroassembly
    container_name: retroassembly
    ports:
        - 8010:8000
    volumes:
        - /volume1/SlowHDD/games:/app/data
    restart: unless-stopped
