version: '3.8'
services:
  retroassembly:
    image: arianrhodsandlot/retroassembly:v5.260119.1416
    env_file:
      - /volume2/FastSSD/docker/retroassembly/.env
    container_name: retroassembly
    ports:
        - 8010:8000
    volumes:
        - /volume1/SlowHDD/games:/app/data
    restart: unless-stopped
