services:
  homeassistant:
    image: homeassistant/home-assistant@sha256:75ef6851d2e48d366764cdb6b569b7ad8be77dcc8e0d1b9aa508ac90e42d4c58
    container_name: Home-Assistant
    mem_limit: 8g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
     test: curl -f http://localhost:8123/ || exit 1
    network_mode: host
    volumes:
      - /volume2/FastSSD/docker/homeassistant:/config:rw
    environment:
      TZ: Europe/Dublin
    restart: on-failure:5
