services:
  cloudflared:
    image: cloudflare/cloudflared:2026.2.0@sha256:404528c1cd63c3eb882c257ae524919e4376115e6fe57befca8d603656a91a4c
    env_file:
      - /volume2/FastSSD/docker/cloudflare/.env
    container_name: Cloudflare-Tunnel
    restart: unless-stopped
    command: tunnel run
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
    # DELETED: environment section
    # (The container will now find TUNNEL_TOKEN automatically from the env_file)
