services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.2@sha256:e9bcb2ef08d25632ff74344e73a025f4f4bf12718335b196fa0e670cacace8c5
    env_file:
      - /volume2/FastSSD/docker/cloudflare/.env
    container_name: Cloudflare-Tunnel
    restart: unless-stopped
    command: tunnel run
    # DELETED: environment section
    # (The container will now find TUNNEL_TOKEN automatically from the env_file)
