services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1000:10
    environment:
      - TZ=Europe/Dublin
    volumes:
      - /volume2/FastSSD/docker/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: ghcr.io/immich-app/postgres:16-vectorchord0.4.3-pgvectors0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    shm_size: 128mb
    volumes:
      - /volume2/FastSSD/docker/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Dublin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=immichpw
      #- DB_STORAGE_TYPE=HDD #Remove the red # in front of the – DB_STORAGE_TYPE=HDD if your database isn’t stored on SSDs.
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1000:10
    security_opt:
      - no-new-privileges:true
    #mem_limit: 3g # Set container limit to 3GB
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri
    env_file:
      - stack.env
    environment:
      #- NODE_OPTIONS=--max-old-space-size=2000 # Add this line to limit Node.js heap to 2GB
      - TZ=Europe/Dublin
    ports:
      - 8212:2283
    volumes:
      - /volume2/FastSSD/docker/immich/upload:/data:rw
      - /volume1/SlowHDD/photos/Barry_Photos:/mnt/nas-photos:ro # Mount the external library
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    #user: 1000:10   # commented this out on advice from Gemini to allow other DB user processes to run
    security_opt:
      - no-new-privileges:true
    #mem_limit: 2g # Set container limit to 2GB
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri
    env_file:
      - stack.env
    volumes:
      - /volume2/FastSSD/docker/immich/upload:/data:rw
      - /volume2/FastSSD/docker/immich/cache:/cache:rw
      - /volume2/FastSSD/docker/immich/cache:/.cache:rw
      - /volume2/FastSSD/docker/immich/cache:/.config:rw
      - /volume2/FastSSD/docker/immich/matplotlib:/matplotlib:rw
    environment: 
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started