version: '3.8'
services:
  retroassembly:
    image: arianrhodsandlot/retroassembly:v5.260124.0752@sha256:d9bc4ff834617ecfb22a20388df5989cab6420c330ed27c7eafdac4e43400a01
    env_file:
      - /volume2/FastSSD/docker/retroassembly/.env
    container_name: retroassembly
    ports:
        - 8010:8000
    volumes:
        - /volume1/SlowHDD/games:/app/data
    restart: unless-stopped
