services:
  kometa:
    image: kometateam/kometa:latest@sha256:46fc4bdd6f64dbd92655c6495d9f9d1a745845bd60fa13a7283755db48de8bc0
    env_file:
      - /volume2/FastSSD/docker/kometa/.env
    container_name: kometa
    environment:
      - TZ=Europe/London
      # Optional: Run immediately on startup, then every day at 5am
      - KOMETA_run=true
      - KOMETA_times=05:00 
    volumes:
      # Mount your config folder from your Git repository source
      - /volume2/FastSSD/docker/kometa/config:/config
    restart: unless-stopped
    # If using Trakt/Plex/Jellyfin external URLs, you might not need network_mode: host
    # but 'host' is easiest if connecting to local instances via localhost/IP.
    # network_mode: host