services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.1.3@sha256:32c352a235fd10f98b3f64a6a4345d3c0c7f4e8be7810d2e1e867f7fe2e48ba2
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /volume2/FastSSD/docker/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Mount Docker socket as read-only
      - ./data:/app/data
    env_file:
      - /volume2/FastSSD/docker/uptime-kuma/.env
