services:
  cloudflared:
    image: cloudflare/cloudflared:latest@sha256:5bb6a0870686742d00e171f36c892ba91e5994631bc363d808b9ba822262dad6
    env_file:
      - /volume2/FastSSD/docker/cloudflare/.env
    container_name: Cloudflare-Tunnel
    restart: unless-stopped
    command: tunnel run
    # DELETED: environment section
    # (The container will now find TUNNEL_TOKEN automatically from the env_file)
