services:
  dozzle:
    image: amir20/dozzle:v9.0.2
    env_file:
      - /volume2/FastSSD/docker/dozzle/.env
    container_name: Dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9989:8080  # Access it at http://<nas-ip>:9989
    restart: unless-stopped
