services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: Dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9989:8080  # Access it at http://<nas-ip>:9989
    restart: unless-stopped