services:
  portainer:
    image: portainer/portainer-ce
    container_name: Portainer2
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /volume2/FastSSD/docker/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
