services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati:latest@sha256:2dca60ef8a60909f2422595bd08cacdd8bfe03a223b8431d14a3cd0f6af327d8
    env_file:
      - /volume2/FastSSD/docker/duplicati/.env
    container_name: duplicati
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 8200:8200
    volumes:
      - /volume2/FastSSD/docker/duplicati/config:/config:rw
      - /volume2/FastSSD/docker/duplicati/backups:/backups:rw
      - /volume1/SlowHDD:/source:rw
    environment:
      - TZ=Europe/Dublin
      - PUID=1000
      - PGID=10
    restart: on-failure:5
