services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.15.1@sha256:c4e02d2c511847eebbda8e0e370b41c78e7b51247353de79340e06c3e95f11be
    container_name: Frigate
    hostname: frigate
    restart: on-failure:5
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    shm_size: 512mb
    environment:
      - TZ=Europe/Dublin
      - FRIGATE_RTSP_PASSWORD=${RTSP_PASS}
    devices:
      - /dev/dri/renderD128 # Excellent for your Intel N100 (OpenVINO/HW Accel)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/FastSSD/docker/frigate/config:/config:rw
      - /volume1/SlowHDD/photos/Frigate_Cameras:/media/frigate:rw
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000 # 1GB Cache
    ports:
      - 5563:5000      # Web UI
      - 8554:8554      # RTSP feeds
      - 8555:8555/tcp  # WebRTC
      - 8555:8555/udp  # WebRTC
