services:
  uptime-kuma:
    image: louislam/uptime-kuma:2@sha256:4c364ef96aaddac7ec4c85f5e5f31c3394d35f631381ccbbf93f18fd26ac7cba
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /volume2/FastSSD/docker/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # Optional: Allows monitoring of other Docker containers directly
    env_file:
      - /volume2/FastSSD/docker/uptime-kuma/.env