services:
  mariadb:
    image: mariadb:12.2-noble@sha256:b1cb255a9939d28a1856815f0de6046c20c28c21b92a9f2696bc782b247a47ee
    env_file:
      - /volume2/FastSSD/docker/booklore/.env
    container_name: BookLore-DB
    networks:
      - web_proxy # Join the same network so BookLore can find it
    security_opt:
      - no-new-privileges:true
    hostname: booklore-db
    environment:
      # DELETED: MARIADB_DATABASE, USER, PASSWORD, ROOT_PASSWORD (Now loaded from env_file)
      - TZ=Europe/Dublin
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - booklore_db_data:/var/lib/mysql
    restart: on-failure:5
    
  booklore:
    image: ghcr.io/booklore-app/booklore:latest@sha256:e5a6ce297a8f255f38d0b68e42c077c01d6edda009678a21b687570f09e9dc93
    env_file:
      - /volume2/FastSSD/docker/booklore/.env
    container_name: BookLore
    mem_limit: 1g
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 6060 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      - USER_ID=1000
      - GROUP_ID=10
      - TZ=Europe/Dublin
      - DATABASE_URL=jdbc:mariadb://BookLore-DB:3306/booklore
      # DELETED: DATABASE_USERNAME and DATABASE_PASSWORD (Now loaded from env_file)
      - JAVA_OPTS=-Xmx768m
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 6060:6060
    volumes:
      - /volume2/FastSSD/docker/booklore/data:/app/data:rw
      - /volume1/SlowHDD/books:/books:ro
      - /volume2/FastSSD/docker/booklore/bookdrop:/bookdrop:rw
    restart: on-failure:5
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
volumes:
  booklore_db_data:
