services:
  emby:
    image: emby/embyserver:latest
    container_name: Emby
    environment:
      - TZ=Europe/Dublin
      - UID=${PUID}
      - GID=${PGID}
      - GIDLIST=${HW_ACCEL_GROUPS}
    volumes:
      - /volume1/docker/embyht/config:/config:rw
      - /volume1/SlowHDD/tvseries:/tvshows:rw
      - /volume1/SlowHDD/music:/music:rw
      - /volume1/SlowHDD/movies:/movies:rw
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: on-failure:5
    network_mode: host
    # ports:  <-- Ignored when using 'host' network mode
    #   - 8096:8096
    #   - 8920:8920
