services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing:latest@sha256:b99c94153e006bca7dcbcb1142879f27cceaf5ca149f593259731871aaaf6be3
    env_file:
      - /volume2/FastSSD/docker/syncthing/.env
    container_name: Syncthing
    healthcheck:
     test: curl -f http://localhost:8384/ || exit 1
    restart: on-failure:5
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=10
      - TZ=Europe/Dublin
    volumes:
      - /volume2/FastSSD/docker/syncthing/config:/config:rw
      - /volume1/SlowHDD:/data1:rw
      - /volume2/FastSSD/docker/syncthing/data2:/data2:rw
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
